name: tests
on: [push]

jobs:
  build:

    name: ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Clone GTest
        run:  git clone https://github.com/google/googletest.git -b release-1.10.0
      - name: Install gtest manually
        working-directory: ./googletest
        run:  sudo apt install python3-pip &&
              cmake . &&
              make &&
              sudo make install

      - name: Install GTest
        run: sudo apt-get install libgtest-dev -y 

      - name: Install Scan-build  
        run: sudo apt-get install -y clang-tools

      - name: Valgrind install
        run: sudo apt-get update && sudo apt-get install -y valgrind 

      - name: Scan-build + Run + Valgrind
        run: cd ./qt/lib && mkdir build && bash ./st.bash  

      - name: gen coverage
        run: sudo apt-get install lcov && cd /build && lcov -t "Tests" -o coverage.info -c -d ./ 

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./build/coverage.info  
